---
apiVersion: "idp.cardlytics.com/v1"
kind: "K8sService"
metadata:
  name: "csa-service"
  team: "publisher-team"
  description: null
  labels:
    tier: "backend"
  links:
  - title: "GitHub Repository"
    url: "https://github.com/cardlytics/publisher-team"
    icon: "github"
spec:
  type: "k8s-service"
  runtime:
    framework: "python"
    buildTool: "npm"
  ports:
  - name: "http"
    port: 8080
  resources:
    cpu: "250m"
    memory: "512Mi"
    cpuLimit: "1000m"
    memoryLimit: "1Gi"
  scaling:
    minReplicas: 2
    maxReplicas: 10
    targetCpuUtilization: 70
  healthCheck:
    path: "/health"
    port: 8080
  dependencies: []
  environments:
    dev:
      replicas: 1
      env: {}
    uat:
      replicas: 2
      env: {}
    prod:
      replicas: 2
      env: {}
