---
replicas: 1
resources:
  cpu: "250m"
  memory: "512Mi"
  cpuLimit: "1000m"
  memoryLimit: "1Gi"
envVars:
  INV_US_347: "BM Policy"
probes:
  liveness:
    httpGet:
      path: "/health/live"
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readiness:
    httpGet:
      path: "/health/ready"
      port: 8080
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
