---
apiVersion: "idp.cardlytics.com/v1"
kind: "K8sService"
metadata:
  name: "tvc-service"
  team: "publisher-team"
  description: "tvc-service service"
  labels:
    golden-path: "true"
    runtime: "kotlin_gradle"
  links: []
spec:
  runtime:
    framework: "spring-boot"
    version: "3.4"
  environmentFiles: true
